feat: skip python installation if exist

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -27,8 +27,18 @@ jobs:
 
     - name: Install dependencies
       run: |
-        python -m pip install --upgrade pip
-        pip install notebook nbconvert
+        if ! command -v python &> /dev/null; then
+          echo "Python not found. Installing Python and dependencies..."
+          python -m pip install --upgrade pip
+          pip install notebook nbconvert pathlib urllib3
+        else
+          echo "Python is already installed. Checking dependencies..."
+          python -c "import notebook, nbconvert, pathlib, urllib3" || (
+            echo "Some dependencies are missing. Installing them..."
+            python -m pip install --upgrade pip
+            pip install notebook nbconvert pathlib urllib3
+          )
+        fi
 
     - name: Run Jupyter Notebook
       run: |
